name: Update ICS

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    # Add permission to push to the repository
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          # This is important for the action to have write access
          token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Run scraper
        run: node dist/scrape.js

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add calendar.ics
          git commit -m "Update calendar" || echo "No changes"
          git push