name: Update Team ICS

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:
    inputs:
      config_file:
        description: 'Path to config file (relative to repo root)'
        required: false
        default: 'team-config.json'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Run team scraper
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.event.inputs.config_file }}" != "team-config.json" ]; then
            node dist/team-scraper.js --config="${{ github.event.inputs.config_file }}"
          else
            node dist/team-scraper.js
          fi

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Stage all ics files
          git add *.ics
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Fetch latest changes
          git fetch origin main
          
          # Create a temporary commit
          git commit -m "Temporary commit"
          
          # Pull with rebase
          git pull --rebase origin main
          
          # Amend the commit message
          git commit --amend -m "Update team calendar"
          
          # Push the changes
          git push
