name: Update Venue Calendars

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Build TypeScript
        run: npm run build:node

      - name: Run venue scraper
        run: node dist/scrapers/venue-scraper.js

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Stage changed files
          git add data/venue/*.json

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update venue calendar data"
          git pull --rebase origin main
          git push
