name: Update Laget Calendar

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Run laget scraper
        run: node dist/scrapers/laget-scraper.js

      - name: Generate ICS files
        run: node dist/cli/generate-ics.js

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Stage the laget data and ICS files
          git add data/laget/*.json public/laget/*.ics
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "Update laget calendar"
          git pull --rebase origin main
          git push
